
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A.R COM
 */
public class insert extends javax.swing.JFrame {

    String r3;
    int rol;
    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
        
    }

    public insert(String a) {
        initComponents();
        r3=a;
        //jTextField3.setText(r3);
        
    }
    public void Insert_table(){
        String t1=jTextField1.getText();
        String t2=jTextField2.getText();
        int t=Integer.parseInt(t1);
           
            try{
            
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/table3","root","");
            Statement stmt=con.createStatement();
            String sql2="select * from participant2";
            ResultSet rs=stmt.executeQuery(sql2);
            
            while(rs.next()){
            rol=Integer.parseInt(""+rs.getInt(1));
            
            if(t==rol){
                try{
                sql2 = "INSERT INTO result(regno,name,event,position) VALUES ('"+t+"','"+rs.getString(2)+"','"+rs.getString(3)+"','"+t2+"')";
            stmt.executeUpdate(sql2);
                resulttable2 rt=new resulttable2();
            rt.setVisible(true);
            dispose();
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"The REG_NO you entered is already in the result list");
           
                }
            }
            }
            
            /*while(rs.next()){
            rol=Integer.parseInt(""+rs.getInt(1));
            
            if(t2.equalsIgnoreCase("speedprogramming")){
                if((rol==t)&&((rs.getString(2)).equalsIgnoreCase(t2))){
                sql2 = "INSERT INTO rspeedprogramming(regno,event,position) VALUES ('"+t+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
                }
            
                }
            
            
            if(t2.equalsIgnoreCase("robotics")){
                if((rol==t)&&((rs.getString(2)).equalsIgnoreCase(t2))){
                
                sql2 = "INSERT INTO rrobotics(regno,event,position) VALUES ('"+t+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
                
            }
            if(t2.equalsIgnoreCase("logodesign")){
                if((rol==t)&&((rs.getString(2)).equalsIgnoreCase(t2))){
                sql2 = "INSERT INTO rlogodesign(regno,event,position) VALUES ('"+t+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
                
            }
            if(t2.equalsIgnoreCase("cricket")){
                if((rol==t)&&((rs.getString(2)).equalsIgnoreCase(t2))){
                sql2 = "INSERT INTO rcricket(regno,event,position) VALUES ('"+t+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
                
            }
            if(t2.equalsIgnoreCase("fifa")){
                if((rol==t)&&((rs.getString(2)).equalsIgnoreCase(t2))){
                sql2 = "INSERT INTO rfifa(regno,event,position) VALUES ('"+t+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
                
            }
            if(t2.equalsIgnoreCase("needforspeed")){
                if((rol==t)&&((rs.getString(2)).equalsIgnoreCase(t2))){
                sql2 = "INSERT INTO rneedforspeed(regno,event,position) VALUES ('"+t+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
                
            }
            if(t2.equalsIgnoreCase("counterstrike")){
                if((rol==t)&&((rs.getString(2)).equalsIgnoreCase(t2))){
                sql2 = "INSERT INTO rcounterstrike(regno,event,position) VALUES ('"+t+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
                
            }
            
            }*/   
            JOptionPane.showMessageDialog(null,"The REG_NO you is not in the particicpant's list");
            stmt.close();
            con.close();
            
        }
        catch(Exception e){
            System.out.println(e);
           }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 550));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("POSITION");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REG NO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        result res=new result();
        res.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Insert_table();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
