
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A.R COM
 */
public class newparticipant extends javax.swing.JFrame {

    
    String r3;
    int reg;
    int spid;
    String t1,t2,t3;
    /**
     * Creates new form newparticipant
     */
    public newparticipant() {
        initComponents();
        
    }

    public newparticipant(String a) {
        initComponents();
        r3=a;
        jTextField2.setText(r3);
        
    }

    public void Insert_table(){
        t1=jTextField3.getText();
        t2=jTextField2.getText();
        t3=jTextField4.getText();
        
        try{
            
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/table3","root","");
            Statement stmt=con.createStatement();
            String sql="select * from participant2";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next()){
                reg=rs.getInt(1);
            }
            reg++;
            sql = "INSERT INTO participant2(regno,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql);
            String sql2="select * from speedpro";
            ResultSet rs2=stmt.executeQuery(sql2);
            
            if(t2.equalsIgnoreCase("speedprogramming")){
                spid=reg;
                sql2 = "INSERT INTO speedpro(spid,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
            
            if(t2.equalsIgnoreCase("robotics")){
                spid=reg;
                sql2 = "INSERT INTO robotics(rid,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
            
            if(t2.equalsIgnoreCase("logodesign")){
                spid=reg;
                sql2 = "INSERT INTO logodesign(lid,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
            
            if(t2.equalsIgnoreCase("cricket")){
                spid=reg;
                sql2 = "INSERT INTO cricket(cid,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
            
            if(t2.equalsIgnoreCase("fifa")){
                spid=reg;
                sql2 = "INSERT INTO fifa(fid,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
            
            if(t2.equalsIgnoreCase("needforspeed")){
                spid=reg;
                sql2 = "INSERT INTO needforspeed(nid,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
            
            if(t2.equalsIgnoreCase("counterstrike")){
                spid=reg;
                sql2 = "INSERT INTO counterstrike(csid,name,event,cnic) VALUES ('"+reg+"','"+t1+"','"+t2+"','"+t3+"')";
            stmt.executeUpdate(sql2);
            }
                
            stmt.close();
            con.close();
            participant part=new participant(r3);
            part.setVisible(true);
            dispose();
            stmt.close();
            con.close();
            
        }
        catch(Exception e){
            
        }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 580));
        setPreferredSize(new java.awt.Dimension(810, 580));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 104, 42, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EVENT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(44, 210, 48, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CNIC");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(44, 319, 38, 17);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(207, 207, 408, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(207, 101, 408, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(207, 316, 408, 30);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        newparticipant1 npart=new newparticipant1(r3);
        npart.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Insert_table();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newparticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newparticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newparticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newparticipant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newparticipant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
