
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A.R COM
 */
public class newparticipant1 extends javax.swing.JFrame {
    String r3;
    String z;
    /**
     * Creates new form newparticipant1
     */
    public newparticipant1() {
        initComponents();
        //z="22/4/2017 ";
        z="03/05/2017 ";
        
        jLabel1.setText(z);
        slidelabelcolor();
        
    }

    public newparticipant1(String a) {
        initComponents();
        r3=a;
        //z="22/4/2017";
        z="03/05/2017 ";
        jLabel1.setText(z);
        slidelabelcolor();
        
    }
    
    public void slidelabelcolor(){
        new Thread(){
            int count;
    
        public void run(){
            try{
                while(true){
                    switch(count){
                       case 0:{
                           Thread.sleep(300);
                           jLabel1.setForeground(Color.BLUE);
                            count=1;
                            break;
                        }
                        
                        case 1:{
                        Thread.sleep(300);
                        jLabel1.setForeground(Color.ORANGE);
                        count=2;
                            break;    
                        }
                        case 2:{
                        Thread.sleep(300);
                        jLabel1.setForeground(Color.GREEN);
                             count=3;
                            break;
                        }
                        
                        case 3:{
                        Thread.sleep(300);
                        jLabel1.setForeground(Color.CYAN);
                             count=4;
                            break;
                        }
                        case 4:{
                        Thread.sleep(300);
                        jLabel1.setForeground(Color.PINK);
                             count=0;
                            break;
                        }
                    }
                }
            }
            catch(Exception e){
                
            }
        }
    }.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(490, 368));
        setPreferredSize(new java.awt.Dimension(490, 368));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("22/7/2017");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 0, 240, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAST DATE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 190, 70);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("NEW PARTICIPANT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(64, 74, 270, 41);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setText("LIST OF PARTICIPANT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(64, 147, 270, 41);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    Calendar cal=new GregorianCalendar();
    int day=cal.get(Calendar.DAY_OF_MONTH);
    int month=cal.get(Calendar.MONTH);
    int year=cal.get(Calendar.YEAR);
    String ss=z.substring(0,2);
    int iz=Integer.parseInt(ss);
    String ss1=z.substring(3,5);
    int iz1=Integer.parseInt(ss1);
    String ss2=z.substring(6,10);
    int iz2=Integer.parseInt(ss2);
    
        if((iz2-year)>0){
        newparticipant npart=new newparticipant(r3);
        npart.setVisible(true);
        dispose();
        }
        
        
        
        
        
        if((iz2-year)>=0){
        if((iz1-month)>0){
        newparticipant npart=new newparticipant(r3);
        npart.setVisible(true);
        dispose();
        }
        }
        
        
        
        if((iz2-year)>=0){
        if((iz1-month)>=0){
        if((iz-day)>=0){
        newparticipant npart=new newparticipant(r3);
        npart.setVisible(true);
        dispose();
        }
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        participant part=new participant(r3);
        part.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(r3.equals("cricket")){
        cricket cr=new cricket();
        cr.setVisible(true);
        dispose();
        }
        if(r3.equals("fifa")){
        fifa f=new fifa();
        f.setVisible(true);
        dispose();
        }
        if(r3.equals("counterstrike")){
        cs c=new cs();
        c.setVisible(true);
        dispose();
        }
        if(r3.equals("needforspeed")){
        nfs n=new nfs();
        n.setVisible(true);
        dispose();
        }
        if(r3.equals("speedprogramming")){
        sp s=new sp();
        s.setVisible(true);
        dispose();
        }
        if(r3.equals("robotics")){
        robotics r=new robotics();
        r.setVisible(true);
        dispose();
        }
        if(r3.equals("logodesign")){
        ld l=new ld();
        l.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newparticipant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newparticipant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newparticipant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newparticipant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newparticipant1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
