/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A.R COM
 */
import AppPackage.AnimationClass;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;




    public class volview extends javax.swing.JFrame {

        public AnimationClass ac=new AnimationClass();

        String r1;
        String r2;
        String r3;
        String op;
    /**
     * Creates new form volview
     */
    public volview() {
        initComponents();
        slidelabelcolor();
    }

    public volview(String s3){
            initComponents();
    
        r3=""+s3;
        slidelabelcolor();
    }
    public volview(String s1,String s3){
            initComponents();
    
        r1=""+s1;
        r3=""+s3;
        slidelabelcolor();
    }
    public void slidelabelcolor(){
        new Thread(){
            int count;
    
        public void run(){
            try{
                while(true){
                    switch(count){
                       case 0:{
                           Thread.sleep(300);
                             MatteBorder border = BorderFactory.createMatteBorder(5,5,5,5,Color.BLUE);
                             jLabel1.setBorder(border);    
                            count=1;
                            break;
                        }
                        
                        case 1:{
                        Thread.sleep(300);
                             MatteBorder border = BorderFactory.createMatteBorder(5,5,5,5,Color.RED);
                             jLabel1.setBorder(border);    
                            count=2;
                            break;    
                        }
                        case 2:{
                        Thread.sleep(300);
                             MatteBorder border = BorderFactory.createMatteBorder(5,5,5,5,Color.GREEN);
                             jLabel1.setBorder(border);    
                            count=3;
                            break;
                        }
                        
                        case 3:{
                        Thread.sleep(300);
                             MatteBorder border = BorderFactory.createMatteBorder(5,5,5,5,Color.CYAN);
                             jLabel1.setBorder(border);    
                            count=4;
                            break;
                        }
                        case 4:{
                        Thread.sleep(300);
                             MatteBorder border = BorderFactory.createMatteBorder(5,5,5,5,Color.ORANGE);
                             jLabel1.setBorder(border);    
                            count=1;
                            break;
                        }
                    }
                }
            }
            catch(Exception e){
                
            }
        }
    }.start();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 510));
        setPreferredSize(new java.awt.Dimension(880, 510));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 240, 170, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 240, 170, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 240, 170, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("VIEW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 240, 170, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(380, 390, 110, 40);

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 128, 137)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 180, 630, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("FOR ADMIN USE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 110, 310, 50);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        op="i";
        adminvolunteer obj=new adminvolunteer(op);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        op="u";
        adminvolunteer obj=new adminvolunteer(op);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        op="d";
        adminvolunteer obj=new adminvolunteer(op);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        volunteer vol=new volunteer();
        vol.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        event ev=new event();
        ev.setVisible(true);
        dispose();
        /*        if(r3.equals("cricket")){
            cricket cr=new cricket();
            cr.setVisible(true);
            dispose();
        }
        if(r3.equals("fifa")){
            fifa f=new fifa();
            f.setVisible(true);
            dispose();
        }
        if(r3.equals("counterstrike")){
            cs c=new cs();
            c.setVisible(true);
            dispose();
        }
        if(r3.equals("needforspeed")){
            nfs n=new nfs();
            n.setVisible(true);
            dispose();
        }
        if(r3.equals("speedprogramming")){
            sp s=new sp();
            s.setVisible(true);
            dispose();
        }
        if(r3.equals("robotics")){
            robotics r=new robotics();
            r.setVisible(true);
            dispose();
        }
        if(r3.equals("logodesign")){
            ld l=new ld();
            l.setVisible(true);
            dispose();
        }*/

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(volview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(volview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(volview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(volview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new volview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
